### ISSUE TITLE
Can't run ModbusMechanic v3.0 on Rocky Linux 9.4

### ISSUE THREAD

**Issue by snowuyl** [SciFiDryer/ModbusMechanic#24]
**Describe the bug**

**To Reproduce**
1. wget https://github.com/SciFiDryer/ModbusMechanic/releases/download/v3.0/ModbusMechanic.v3.0.zip
2. unzip ./ModbusMechanic.v3.0.zip 
3. cd ModbusMechanic/
4. java -jar ModbusMechanic.jar -debug

**Expected behavior**
Can run ModbusMechanic on Rocky Linux 9 successfully.

**Desktop (please complete the following information):**
 - OS: Rocky Linux
 - Version: 9.4

**Java Runtime Version**

openjdk 11.0.25 2024-10-15 LTS
**Additional context**
java -jar ModbusMechanic.jar -debug
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-11.0.25.0.9-2.el9.x86_64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1854)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2450)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2506)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2705)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2656)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1890)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1399)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1397)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1396)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1429)
	at java.desktop/java.awt.Component.<clinit>(Component.java:621)
	at modbusmechanic.ModbusMechanic.main(ModbusMechanic.java:116)

**Comment by zachelnet** [comment]
Hi @snowuyl 

try following command, on my Fedora 43 works:
´´´
/usr/lib/jvm/java-17-zulu-openjdk-jdk/bin/java -Dsun.java2d.uiScale=2 -jar /home/mzach/bin/ModbusMechanic.jar
´´´
